Geomarks are listed
bcgov/smk pull request #131
Opened 2021-10-12 20:36 UTC by michaelpnelson

As geomarks are created, they are added to a list. Each geomark in the list can be toggled on and off.

2021-10-13 23:24 UTC, dgboss requested changes

2021-10-13 23:24 UTC, dgboss commented on src/smk/tool/geomark/panel-geomark.html
> +    <h2>Loaded Geomarks</h2>
Could we hide this when there are no Geomarks in the list?

2021-10-13 23:24 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +            this.defineProp( 'geomarks' )
Could you please add a semi-colon at the end of these lines?

2021-10-13 23:24 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +            var currentDrawingLayer = self.createCurrentDrawingLayer();
Stylistic thing, but how do you feel about initializing all the variables in a given scope at the same location (eg move this up to line 33 and move 'var client' at line 105 up as well)? Versus sprinkling them throughout?

2021-10-13 23:24 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                        matchingGeomark = item;
Can we either break out of this for loop when we find a match? Or return the item directly from the for loop?

2021-10-13 23:24 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
>                          self.showStatusMessage('No drawings were found. Draw one or more polygons before creating a geomark.', 'warning');
I didn't catch this in the last PR, but is it possible to increase the delay before the message is dismissed. I think it is a little on the short side right now.

2021-10-13 23:24 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                    if (!geomark) return;
Could you expand this out to
```
if (!geomark) {
    return;
}
```

2021-10-14 15:14 UTC, michaelpnelson commented on src/smk/tool/geomark/panel-geomark.html
> +    <h2>Loaded Geomarks</h2>
Good suggestion! 

I looked at what the Firewood app does, and I will copy that functionality: when no geomarks have been created/loaded, it displays "No geomarks have been loaded.".

2021-10-14 15:22 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +            this.defineProp( 'geomarks' )
Sure. I'm assuming we want to do end lines in semicolons in general? I've been doing this mostly but I'm sure I forget at times.

At some point we can consider adding a linter to this project to help us stay consistent on style.

2021-10-14 15:31 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +            var currentDrawingLayer = self.createCurrentDrawingLayer();
My biggest counter-argument is readability: for someone new to the code, the variable is defined closely to where it is used, whereas if all variables were defined in the same place near the top, the reader starting far down has to go way up to see the definition.

I prefer to keep functions small to begin with, so where I can I like to break long functions into smaller ones. This one is pretty long already and there's much more code to come :) .

2021-10-14 15:51 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                        matchingGeomark = item;
Thanks; this is inefficient.

I revisited the methods on Array, and I think Array.find() works well here - it looks like an even simpler solution - so I'll use that.

2021-10-14 15:55 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
>                          self.showStatusMessage('No drawings were found. Draw one or more polygons before creating a geomark.', 'warning');
Sure, I'll increase it to 5 seconds (like the other usages of "showStatusMessage" here) from the default of 2 seconds.

2021-10-14 16:02 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                    if (!geomark) return;
Done.

2021-10-15 15:52 UTC, dgboss commented on src/smk/tool/geomark/panel-geomark.html
> +    <h2>Loaded Geomarks</h2>
My suggestion would be to hide this portion of the UI until a Geomark is actually drawn/created or loaded. The current phrasing in the Firewood DMF app could be confusing if a user's intent is to draw a new Geomark and not 'load' an existing one.

2021-10-15 16:03 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
>              this.buildLngLatCoords = function(layerGroup) {
I've discovered that this function doesn't generate valid WKT geometries for multiple polygons. No need to fix as part of this PR, but could you please file an issue to address in the future? To reproduce:
1. Draw two polygons on the map
2. Click 'Save drawing as a Geomark
3. Copy the generated URL
4. Open the URL in a browser and look for the 'Is Valid Geometry' field which will have a value of false.

eg. https://apps.gov.bc.ca/pub/geomark/geomarks/gm-E7B27F0F92C844AEB632E67E0D15B5C1

2021-10-15 16:04 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +            var currentDrawingLayer = self.createCurrentDrawingLayer();
Your choice!

2021-10-15 16:05 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
>                  var type = e.layerType;
It doesn't look like this is used anywhere (var type = e.layerType;). I think you can delete it.

2021-10-15 18:47 UTC, michaelpnelson commented on src/smk/tool/geomark/panel-geomark.html
> +    <h2>Loaded Geomarks</h2>
Done.

2021-10-15 18:52 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
>              this.buildLngLatCoords = function(layerGroup) {
I've observed this as well. My code doesn't work well with multipolygons. 

This will be addressed in a forthcoming pull request where the ability to load a geomark is added. Instead of parsing geometries myself I'll be using a library.

2021-10-15 18:56 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
>                  var type = e.layerType;
Good catch! Removed.

2021-10-18 16:51 UTC, dgboss commented on src/smk/tool/geomark/panel-geomark.html
> +        </ul>
I think there is room for some improvement of the UI. I don't think an unordered list needs to used to display the geomarks. I feel that checkboxes with a slight indentation would be sufficient. Thoughts?
 
Also, the name of the geomark ends up getting truncated. Can you come up with a way to either fit the entire geomark name within the panel, or perhaps truncate with ellipsis and show the full name on hover?

![image](https://user-images.githubusercontent.com/7094320/137774523-79f03d79-668d-42f2-a339-a5cd25d5cab3.png)

2021-10-18 18:32 UTC, dgboss commented on src/smk/tool/geomark/panel-geomark.html
> +        </ul>
The bullets are being removed and further enhancements to the UI are being deferred.

2021-10-18 18:32 UTC, dgboss approved these changes
.

2021-10-18 18:48 UTC, michaelpnelson commented on src/smk/tool/geomark/panel-geomark.html
> +        </ul>
Done. In the next commit, the bullets are removed from the list items and extra space before items is removed; and item text is truncated with ellipses. ul and li tags remain to continue to identify this semantically as a list for non-visual processing.

2021-10-18 19:00 UTC, merged