Can load a geomark from a URL
bcgov/smk pull request #132
Opened 2021-10-18 22:02 UTC by michaelpnelson

2021-10-19 15:52 UTC, dgboss requested changes
It's working great!

One request that I neglected to mention in the previous PR (listing geomarks), could you please have the hyperlinks for geomarks open in new tabs/windows instead of in the current tab? Thanks!

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                        self.showStatusMessage('Geomark ' + geomarkId + ' is already loaded.', 'warning');
What do you think about extending the length of time the message is visible for to 5 seconds?

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                        cache: false,
Is there a reason we don't want the browser caching the response?

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                            var polygon = L.geoJSON(geomarkFeature.geometry).addTo(smk.$viewer.map);
Will this always be a polygon? Or can we also load point and line geomarks? What do you think about naming this to help indicate that 'polygon' is actually a layer of some sort? I didn't realize it was a layer until later on when I saw it passed to another function and then I looked at that function's signature.

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                            var polygon = L.geoJSON(geomarkFeature.geometry).addTo(smk.$viewer.map);
Is the result of L.geoJson() guranteed to be defined? ie. Will we never see a undefined error when the .addTo() call is made?

In general, I'm not a huge fan of chaining functions together as it is easy to run into the situation I'm asking about.

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                if (!geomarkUrl) return;
Could you expand this if statement please?
```
if (!geomarkUrl) {
  return;
}
```

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                var lastSlashIdx = trimmedUrl.lastIndexOf('/');
A trivial readability thing, but I'd suggest just spelling out 'index' within the variable name.

2021-10-19 15:52 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                var lastSlashIdx = trimmedUrl.lastIndexOf('/');
It's quite common for people to include a trailing slash on a URL. This line will cause the addition of a geomark to fail if the user includes a trailing slash, with no indication as to why the attempt failed. I would suggest handling this situation in some way.

2021-10-19 18:17 UTC, michaelpnelson commented
> One request that I neglected to mention in the previous PR (listing geomarks), could you please have the hyperlinks for geomarks open in new tabs/windows instead of in the current tab? Thanks!

Done.

2021-10-19 18:22 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                        self.showStatusMessage('Geomark ' + geomarkId + ' is already loaded.', 'warning');
Of the messages, this one is quite short and quick to digest, so I thought the default of 2 seconds is adequate, but I can extend it.

We might consider increasing the 2 second default at some point.

2021-10-19 18:27 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                        cache: false,
No reason - I just copied the settings used by the client (https://apps.gov.bc.ca/pub/geomark/js/geomark.js).

Given that a geomark is read-only, I don't see the value of preventing caching because we wouldn't expect the response to have changed data. I'll remove the "cache" parameter as it is true by default.

2021-10-19 18:42 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                            var polygon = L.geoJSON(geomarkFeature.geometry).addTo(smk.$viewer.map);
I will rename "polygon" because it could be a line or a point (I tested a line but the geomark service didn't accept my point so that may not be supported by geomarks).

About L.geoJson() ... I did some testing, and if I give it garbage data, nothing breaks in the app, the layer doesn't load, and the console logs an error: "Invalid GeoJSON object.". We could trap for it, but I'm not sure we need to be validating the response data, and should there ever be a problem with response data, logging the error seems a good way to expose it.

2021-10-19 18:44 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                if (!geomarkUrl) return;
Done.

2021-10-19 21:04 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                var lastSlashIdx = trimmedUrl.lastIndexOf('/');
I've renamed the variable to include the full word "index".

Good point about the trailing slash. I've added validation code that will trim a trailing slash. I realized we should also attempt to prevent malicious data so I added other sanitation code to encode characters and remove query parameters. 

I considered adding validation that the geomark ID begin with "gm-", but I hesitate to in case there are legacy geomarks without this pattern, or if the pattern changes.

2021-10-19 22:30 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                        cache: false,
Sounds good

2021-10-19 22:32 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                        self.showStatusMessage('Geomark ' + geomarkId + ' is already loaded.', 'warning');
I'm a slow reader. Thanks for changing!

2021-10-19 22:35 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                if (url.endsWith('/') && url.length > 0) {
I don't think this condition is necessary. If an URL ends with a '/' character, it will always have length greater than 0.

2021-10-19 22:35 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +                var lastSlashIdx = trimmedUrl.lastIndexOf('/');
Excellent!

2021-10-19 22:40 UTC, dgboss requested changes
One more small tweak and it's good to go!

2021-10-19 22:44 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +                if (url.endsWith('/') && url.length > 0) {
Good point!

2021-10-20 15:25 UTC, dgboss approved these changes
.

2021-10-20 15:30 UTC, merged