Command links are replaced with buttons
bcgov/smk pull request #142
Opened 2021-11-18 23:05 UTC by michaelpnelson

2021-11-18 23:08 UTC, michaelpnelson commented on src/smk/tool/geomark/panel-geomark.html
> +    <div v-if="geomarks.length !== 0" id="geomarks-container">
This isn't related but I thought I'd update this while I noticed that I've been using === for equality but != for inequality. I fixed it elsewhere as well.

2021-11-22 23:09 UTC, dgboss commented
The changes look good, though I did come up with one use case that is a little odd. Try the following:
1. Enable the Geomark tool/panel
2. Draw a polygon on the map, but don't save it
3. Close the geomark panel
4. Re-open the geomark panel. I would expect the buttons to still be active since I have an unsaved geomark on my map, but they are inactive.

2021-11-22 23:11 UTC, dgboss requested changes
The changes look good, though I did come up with one use case that is a little odd. Try the following:

1. Enable the Geomark tool/panel
2. Draw a polygon on the map, but don't save it
3. Close the geomark panel
4. Re-open the geomark panel. I would expect the buttons to still be active since I have an unsaved geomark on my map, but they are inactive.

2021-11-22 23:34 UTC, michaelpnelson commented
> The changes look good, though I did come up with one use case that is a little odd. Try the following:
> 
> 1. Enable the Geomark tool/panel
> 2. Draw a polygon on the map, but don't save it
> 3. Close the geomark panel
> 4. Re-open the geomark panel. I would expect the buttons to still be active since I have an unsaved geomark on my map, but they are inactive.

Good catch!

The "shapeIsDrawn" variable is set to false on initialization, but it's also set to false when the panel becomes active. I'll remove this line and push another commit.

2021-11-22 23:43 UTC, dgboss approved these changes
Looks good!

2021-11-23 16:46 UTC, merged