Geomark is disabled for mobile devices
bcgov/smk pull request #144
Opened 2021-11-24 16:51 UTC by michaelpnelson

2021-11-24 17:02 UTC, michaelpnelson commented
Some notes from my testing ...

When an SMK app is created with "mobile" specified, the geomark panel doesn't appear, even when enabled in smk-config.json; I believe this is because geomark is not included in the built app (I don't see it among the node module files).

When an SMK app is created with "default" specified, the geomark panel appears for a mobile device, but there's no functionality when it's selected - we don't enter draw mode and buttons don't work. 

We disable other tools this way (coordinate, zoom, markup, minimap) but this may be the first time we've disabled a panel this way. I didn't see a way to exclude the panel from the list of tools for mobile devices; we test on the smk.$device variable, but it looks like we don't have a handle on the smk object until after tools are initialized.

2021-11-24 19:04 UTC, dgboss requested changes

2021-11-24 19:04 UTC, dgboss commented on src/smk/tool/geomark/tool-geomark.js
> +            if ( smk.$device == 'mobile' ) {
We should use === here.

2021-11-24 19:19 UTC, dgboss requested changes
Also consider updating documentation to indicate that the geomoark tool isn't supported when device === mobile.

2021-11-24 19:42 UTC, michaelpnelson commented
> Also consider updating documentation to indicate that the geomoark tool isn't supported when device === mobile.

Done.

2021-11-24 19:42 UTC, michaelpnelson commented on src/smk/tool/geomark/tool-geomark.js
> +            if ( smk.$device == 'mobile' ) {
Done.

2021-11-25 21:25 UTC, dgboss approved these changes
Looks good.

2021-11-25 22:25 UTC, merged